// This file is auto-generated by @hey-api/openapi-ts

export type PagedResultDto_AddressCommonDataDto = {
    items?: Array<UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CityDto = {
    items?: Array<UniRefund_LocationService_Cities_CityDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CountryDateDto = {
    items?: Array<UniRefund_LocationService_CountryDates_CountryDateDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CountryDto = {
    items?: Array<UniRefund_LocationService_Countries_CountryDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CountryNumberDto = {
    items?: Array<UniRefund_LocationService_CountryNumbers_CountryNumberDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CountryTimeDto = {
    items?: Array<UniRefund_LocationService_CountryTimes_CountryTimeDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CurrencyDto = {
    items?: Array<UniRefund_LocationService_Currencies_CurrencyDto> | null;
    totalCount?: number;
};

export type PagedResultDto_DistrictDto = {
    items?: Array<UniRefund_LocationService_Districts_DistrictDto> | null;
    totalCount?: number;
};

export type PagedResultDto_NeighborhoodDto = {
    items?: Array<UniRefund_LocationService_Neighborhoods_NeighborhoodDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RegionalSettingDto = {
    items?: Array<UniRefund_LocationService_RegionalSettings_RegionalSettingDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RegionDto = {
    items?: Array<UniRefund_LocationService_Regions_RegionDto> | null;
    totalCount?: number;
};

export type UniRefund_LocationService_AddressCommonDatas_AddressCommonDataCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    type: UniRefund_LocationService_Enums_AddressType;
    addressLine: string;
    postalCode?: (string) | null;
    primaryFlag?: boolean;
    countryId: string;
    regionId?: (string) | null;
    cityId?: (string) | null;
    districtId?: (string) | null;
    neighborhoodId?: (string) | null;
};

export type UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    type: UniRefund_LocationService_Enums_AddressType;
    addressLine: string;
    postalCode: string;
    fullAddress: string;
    primaryFlag?: boolean;
    countryId: string;
    regionId?: (string) | null;
    cityId: string;
    districtId: string;
    neighborhoodId?: (string) | null;
};

export type UniRefund_LocationService_AddressCommonDatas_AddressCommonDataUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    type: UniRefund_LocationService_Enums_AddressType;
    addressLine: string;
    postalCode: string;
    primaryFlag?: boolean;
    countryId: string;
    regionId?: (string) | null;
    cityId?: (string) | null;
    districtId?: (string) | null;
    neighborhoodId?: (string) | null;
};

export type UniRefund_LocationService_Cities_CityCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    centerLatitudeCoordinate?: (number) | null;
    centerLongitudeCoordinate?: (number) | null;
    elevation?: (number) | null;
    population?: (number) | null;
    isCapital?: boolean;
    isMetropolitan?: boolean;
    plateCode: number;
    timezoneId?: (string) | null;
    regionId: string;
};

export type UniRefund_LocationService_Cities_CityDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    centerLatitudeCoordinate?: (number) | null;
    centerLongitudeCoordinate?: (number) | null;
    elevation?: (number) | null;
    population?: (number) | null;
    isCapital?: boolean;
    isMetropolitan?: boolean;
    plateCode: number;
    regionId: string;
};

export type UniRefund_LocationService_Cities_CityUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    centerLatitudeCoordinate?: (number) | null;
    centerLongitudeCoordinate?: (number) | null;
    elevation?: (number) | null;
    population?: (number) | null;
    isCapital?: boolean;
    isMetropolitan?: boolean;
    plateCode: number;
    timezoneId?: (string) | null;
    regionId: string;
};

export type UniRefund_LocationService_Countries_CountryCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    code3: string;
    code2: string;
    name: string;
    flagUrl?: (string) | null;
    population?: (number) | null;
    isTimezoneCurrentlyDst?: boolean;
    hasRegion?: boolean;
    timezoneId: string;
    countryNumberId: string;
    countryTimeId: string;
    countryDateId: string;
    continent: UniRefund_LocationService_Enums_Continent;
};

export type UniRefund_LocationService_Countries_CountryDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    code3: string;
    code2: string;
    name: string;
    flagUrl?: (string) | null;
    population?: (number) | null;
    isTimezoneCurrentlyDst?: boolean;
    hasRegion?: boolean;
    timezoneId: string;
    countryNumberId: string;
    countryTimeId: string;
    countryDateId: string;
    continent: UniRefund_LocationService_Enums_Continent;
};

export type UniRefund_LocationService_Countries_CountryInfoDto = {
    code3?: (string) | null;
    code2?: (string) | null;
    name?: (string) | null;
};

export type UniRefund_LocationService_Countries_CountryUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    code3: string;
    code2: string;
    name: string;
    flagUrl?: (string) | null;
    population?: (number) | null;
    isTimezoneCurrentlyDst?: boolean;
    hasRegion?: boolean;
    timezoneId: string;
    countryNumberId: string;
    countryTimeId: string;
    countryDateId: string;
    continent: UniRefund_LocationService_Enums_Continent;
};

export type UniRefund_LocationService_Countries_GetCountryNameDto = {
    code2?: (string) | null;
    name?: (string) | null;
};

export type UniRefund_LocationService_CountryDates_CountryDateCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    shortDate: string;
    longDate: string;
    startYearForTwoDigitYear: string;
    endYearForTwoDigitYear: string;
    firstDayOfWeek: UniRefund_LocationService_Enums_FirstDayOfWeek;
    calendarType: UniRefund_LocationService_Enums_CalendarType;
};

export type UniRefund_LocationService_CountryDates_CountryDateDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    shortDate: string;
    longDate: string;
    startYearForTwoDigitYear: string;
    endYearForTwoDigitYear: string;
    firstDayOfWeek: UniRefund_LocationService_Enums_FirstDayOfWeek;
    calendarType: UniRefund_LocationService_Enums_CalendarType;
};

export type UniRefund_LocationService_CountryDates_CountryDateUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    shortDate: string;
    longDate: string;
    startYearForTwoDigitYear: string;
    endYearForTwoDigitYear: string;
    firstDayOfWeek: UniRefund_LocationService_Enums_FirstDayOfWeek;
    calendarType: UniRefund_LocationService_Enums_CalendarType;
};

export type UniRefund_LocationService_CountryNumbers_CountryNumberCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    negativeSignSymbol: string;
    listSeperator: string;
    noOfDigitsAfterDecimal: number;
    displayLeadingZeros: string;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
    negativeNumberFormat: UniRefund_LocationService_Enums_NegativeNumberFormat;
    measurementSystem: UniRefund_LocationService_Enums_MeasurementSystem;
    standardDigits: UniRefund_LocationService_Enums_StandardDigits;
    useNativeDigits: UniRefund_LocationService_Enums_UseNativeDigits;
};

export type UniRefund_LocationService_CountryNumbers_CountryNumberDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    negativeSignSymbol: string;
    listSeperator: string;
    noOfDigitsAfterDecimal: number;
    displayLeadingZeros: string;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
    negativeNumberFormat: UniRefund_LocationService_Enums_NegativeNumberFormat;
    measurementSystem: UniRefund_LocationService_Enums_MeasurementSystem;
    standardDigits: UniRefund_LocationService_Enums_StandardDigits;
    useNativeDigits: UniRefund_LocationService_Enums_UseNativeDigits;
};

export type UniRefund_LocationService_CountryNumbers_CountryNumberUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    negativeSignSymbol: string;
    listSeperator: string;
    noOfDigitsAfterDecimal: number;
    displayLeadingZeros: string;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
    negativeNumberFormat: UniRefund_LocationService_Enums_NegativeNumberFormat;
    measurementSystem: UniRefund_LocationService_Enums_MeasurementSystem;
    standardDigits: UniRefund_LocationService_Enums_StandardDigits;
    useNativeDigits: UniRefund_LocationService_Enums_UseNativeDigits;
};

export type UniRefund_LocationService_CountryTimes_CountryTimeCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    shortTime: string;
    longTime: string;
    amSymbol: string;
    pmSymbol: string;
};

export type UniRefund_LocationService_CountryTimes_CountryTimeDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    shortTime: string;
    longTime: string;
    amSymbol: string;
    pmSymbol: string;
};

export type UniRefund_LocationService_CountryTimes_CountryTimeUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    shortTime: string;
    longTime: string;
    amSymbol: string;
    pmSymbol: string;
};

export type UniRefund_LocationService_Currencies_CurrencyCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    code: string;
    currencySymbol: string;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    noOfDigitsAfterDecimal: number;
    positiveCurrencyFormat: UniRefund_LocationService_Enums_PositiveCurrencyFormat;
    negativeCurrencyFormat: UniRefund_LocationService_Enums_NegativeCurrencyFormat;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
};

export type UniRefund_LocationService_Currencies_CurrencyDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    code: string;
    currencySymbol: string;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    noOfDigitsAfterDecimal: number;
    positiveCurrencyFormat: UniRefund_LocationService_Enums_PositiveCurrencyFormat;
    negativeCurrencyFormat: UniRefund_LocationService_Enums_NegativeCurrencyFormat;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
};

export type UniRefund_LocationService_Currencies_CurrencyUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    code: string;
    currencySymbol: string;
    decimalSymbol: string;
    digitGroupingSymbol: string;
    noOfDigitsAfterDecimal: number;
    positiveCurrencyFormat: UniRefund_LocationService_Enums_PositiveCurrencyFormat;
    negativeCurrencyFormat: UniRefund_LocationService_Enums_NegativeCurrencyFormat;
    digitGrouping: UniRefund_LocationService_Enums_DigitGrouping;
};

export type UniRefund_LocationService_Districts_DistrictCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    cityId: string;
};

export type UniRefund_LocationService_Districts_DistrictDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    population?: (number) | null;
    cityId: string;
};

export type UniRefund_LocationService_Districts_DistrictUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    cityId: string;
};

export type UniRefund_LocationService_Enums_AddressType = 'Home' | 'Office' | 'Invoice' | 'Contact';

export type UniRefund_LocationService_Enums_CalendarType = 'Gregorian' | 'Julian' | 'Hebrew' | 'Islamic' | 'Buddhist' | 'Chinese';

export type UniRefund_LocationService_Enums_Continent = 'Asia' | 'Africa' | 'Europe' | 'NorthAmerica' | 'SouthAmerica' | 'Austrualia' | 'Antarctica';

export type UniRefund_LocationService_Enums_DigitGrouping = 'FormatWithCommas' | 'FormatWithDots';

export type UniRefund_LocationService_Enums_FirstDayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export type UniRefund_LocationService_Enums_MeasurementSystem = 'USCustomary' | 'Metric' | 'Imperial';

export type UniRefund_LocationService_Enums_NegativeCurrencyFormat = 'WithParentheses' | 'WithMinusSign';

export type UniRefund_LocationService_Enums_NegativeNumberFormat = 'MinusBeforeNumber' | 'Parentheses' | 'MinusAfterNumber' | 'UnicodeMinus';

export type UniRefund_LocationService_Enums_PositiveCurrencyFormat = 'WithDollarSign' | 'WithDollarSignAfter' | 'WithCurrencyCodeBefore' | 'WithCurrencyCodeAfter' | 'WithoutCurrencySymbol';

export type UniRefund_LocationService_Enums_StandardDigits = 'AllDigits' | 'DigitsWithoutZero' | 'DigitsReversed';

export type UniRefund_LocationService_Enums_UseNativeDigits = 'Never' | 'Always' | 'Conditional';

export type UniRefund_LocationService_Neighborhoods_NeighborhoodCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    isTown: boolean;
    districtId: string;
};

export type UniRefund_LocationService_Neighborhoods_NeighborhoodDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    population?: (number) | null;
    isTown: boolean;
    districtId: string;
};

export type UniRefund_LocationService_Neighborhoods_NeighborhoodUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    isTown: boolean;
    districtId: string;
};

export type UniRefund_LocationService_RegionalSettings_RegionalSettingCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    regionId: string;
};

export type UniRefund_LocationService_RegionalSettings_RegionalSettingDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    regionId: string;
};

export type UniRefund_LocationService_RegionalSettings_RegionalSettingUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    regionId: string;
};

export type UniRefund_LocationService_Regions_RegionCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    timezoneId?: (string) | null;
    countryId: string;
};

export type UniRefund_LocationService_Regions_RegionDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    population?: (number) | null;
    regionalSetting?: UniRefund_LocationService_RegionalSettings_RegionalSettingDto;
    countryId: string;
};

export type UniRefund_LocationService_Regions_RegionUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    population?: (number) | null;
    timezoneId?: (string) | null;
    regionalSettingId: string;
    countryId: string;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type GetApiLocationServiceAddressCommonDataByIdData = {
    id: string;
};

export type GetApiLocationServiceAddressCommonDataByIdResponse = (UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto);

export type PutApiLocationServiceAddressCommonDataByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_AddressCommonDatas_AddressCommonDataUpdateDto;
};

export type PutApiLocationServiceAddressCommonDataByIdResponse = (UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto);

export type DeleteApiLocationServiceAddressCommonDataByIdData = {
    id: string;
};

export type DeleteApiLocationServiceAddressCommonDataByIdResponse = (unknown);

export type GetApiLocationServiceAddressCommonDataData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceAddressCommonDataResponse = (PagedResultDto_AddressCommonDataDto);

export type PostApiLocationServiceAddressCommonDataData = {
    requestBody?: UniRefund_LocationService_AddressCommonDatas_AddressCommonDataCreateDto;
};

export type PostApiLocationServiceAddressCommonDataResponse = (UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto);

export type GetApiLocationServiceAddressCommonDataGetListWithIdsData = {
    ids?: Array<(string)>;
};

export type GetApiLocationServiceAddressCommonDataGetListWithIdsResponse = (Array<UniRefund_LocationService_AddressCommonDatas_AddressCommonDataDto>);

export type GetApiLocationServiceCitiesData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCitiesResponse = (PagedResultDto_CityDto);

export type PostApiLocationServiceCitiesData = {
    requestBody?: UniRefund_LocationService_Cities_CityCreateDto;
};

export type PostApiLocationServiceCitiesResponse = (UniRefund_LocationService_Cities_CityDto);

export type GetApiLocationServiceCitiesGetListByRegionByRegionIdData = {
    regionId: string;
};

export type GetApiLocationServiceCitiesGetListByRegionByRegionIdResponse = (Array<UniRefund_LocationService_Cities_CityDto>);

export type GetApiLocationServiceCitiesGetListByCountryByCountryIdData = {
    countryId: string;
};

export type GetApiLocationServiceCitiesGetListByCountryByCountryIdResponse = (Array<UniRefund_LocationService_Cities_CityDto>);

export type GetApiLocationServiceCitiesByIdData = {
    id: string;
};

export type GetApiLocationServiceCitiesByIdResponse = (UniRefund_LocationService_Cities_CityDto);

export type PutApiLocationServiceCitiesByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Cities_CityUpdateDto;
};

export type PutApiLocationServiceCitiesByIdResponse = (UniRefund_LocationService_Cities_CityDto);

export type DeleteApiLocationServiceCitiesByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCitiesByIdResponse = (unknown);

export type GetApiLocationServiceCountriesData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCountriesResponse = (PagedResultDto_CountryDto);

export type PostApiLocationServiceCountriesData = {
    requestBody?: UniRefund_LocationService_Countries_CountryCreateDto;
};

export type PostApiLocationServiceCountriesResponse = (UniRefund_LocationService_Countries_CountryDto);

export type GetApiLocationServiceCountriesByIdData = {
    id: string;
};

export type GetApiLocationServiceCountriesByIdResponse = (UniRefund_LocationService_Countries_CountryDto);

export type PutApiLocationServiceCountriesByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Countries_CountryUpdateDto;
};

export type PutApiLocationServiceCountriesByIdResponse = (UniRefund_LocationService_Countries_CountryDto);

export type DeleteApiLocationServiceCountriesByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCountriesByIdResponse = (unknown);

export type GetApiLocationServiceCountryDatesData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCountryDatesResponse = (PagedResultDto_CountryDateDto);

export type PostApiLocationServiceCountryDatesData = {
    requestBody?: UniRefund_LocationService_CountryDates_CountryDateCreateDto;
};

export type PostApiLocationServiceCountryDatesResponse = (UniRefund_LocationService_CountryDates_CountryDateDto);

export type GetApiLocationServiceCountryDatesByIdData = {
    id: string;
};

export type GetApiLocationServiceCountryDatesByIdResponse = (UniRefund_LocationService_CountryDates_CountryDateDto);

export type PutApiLocationServiceCountryDatesByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_CountryDates_CountryDateUpdateDto;
};

export type PutApiLocationServiceCountryDatesByIdResponse = (UniRefund_LocationService_CountryDates_CountryDateDto);

export type DeleteApiLocationServiceCountryDatesByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCountryDatesByIdResponse = (unknown);

export type GetApiLocationServiceCountryNumbersData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCountryNumbersResponse = (PagedResultDto_CountryNumberDto);

export type PostApiLocationServiceCountryNumbersData = {
    requestBody?: UniRefund_LocationService_CountryNumbers_CountryNumberCreateDto;
};

export type PostApiLocationServiceCountryNumbersResponse = (UniRefund_LocationService_CountryNumbers_CountryNumberDto);

export type GetApiLocationServiceCountryNumbersByIdData = {
    id: string;
};

export type GetApiLocationServiceCountryNumbersByIdResponse = (UniRefund_LocationService_CountryNumbers_CountryNumberDto);

export type PutApiLocationServiceCountryNumbersByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_CountryNumbers_CountryNumberUpdateDto;
};

export type PutApiLocationServiceCountryNumbersByIdResponse = (UniRefund_LocationService_CountryNumbers_CountryNumberDto);

export type DeleteApiLocationServiceCountryNumbersByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCountryNumbersByIdResponse = (unknown);

export type GetApiLocationServiceCountryTimesData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCountryTimesResponse = (PagedResultDto_CountryTimeDto);

export type PostApiLocationServiceCountryTimesData = {
    requestBody?: UniRefund_LocationService_CountryTimes_CountryTimeCreateDto;
};

export type PostApiLocationServiceCountryTimesResponse = (UniRefund_LocationService_CountryTimes_CountryTimeDto);

export type GetApiLocationServiceCountryTimesByIdData = {
    id: string;
};

export type GetApiLocationServiceCountryTimesByIdResponse = (UniRefund_LocationService_CountryTimes_CountryTimeDto);

export type PutApiLocationServiceCountryTimesByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_CountryTimes_CountryTimeUpdateDto;
};

export type PutApiLocationServiceCountryTimesByIdResponse = (UniRefund_LocationService_CountryTimes_CountryTimeDto);

export type DeleteApiLocationServiceCountryTimesByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCountryTimesByIdResponse = (unknown);

export type GetApiLocationServiceCurrenciesData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceCurrenciesResponse = (PagedResultDto_CurrencyDto);

export type PostApiLocationServiceCurrenciesData = {
    requestBody?: UniRefund_LocationService_Currencies_CurrencyCreateDto;
};

export type PostApiLocationServiceCurrenciesResponse = (UniRefund_LocationService_Currencies_CurrencyDto);

export type GetApiLocationServiceCurrenciesByIdData = {
    id: string;
};

export type GetApiLocationServiceCurrenciesByIdResponse = (UniRefund_LocationService_Currencies_CurrencyDto);

export type PutApiLocationServiceCurrenciesByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Currencies_CurrencyUpdateDto;
};

export type PutApiLocationServiceCurrenciesByIdResponse = (UniRefund_LocationService_Currencies_CurrencyDto);

export type DeleteApiLocationServiceCurrenciesByIdData = {
    id: string;
};

export type DeleteApiLocationServiceCurrenciesByIdResponse = (unknown);

export type GetApiLocationServiceDistrictsData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceDistrictsResponse = (PagedResultDto_DistrictDto);

export type PostApiLocationServiceDistrictsData = {
    requestBody?: UniRefund_LocationService_Districts_DistrictCreateDto;
};

export type PostApiLocationServiceDistrictsResponse = (UniRefund_LocationService_Districts_DistrictDto);

export type GetApiLocationServiceDistrictsGetListByCityByCityIdData = {
    cityId: string;
};

export type GetApiLocationServiceDistrictsGetListByCityByCityIdResponse = (Array<UniRefund_LocationService_Districts_DistrictDto>);

export type GetApiLocationServiceDistrictsByIdData = {
    id: string;
};

export type GetApiLocationServiceDistrictsByIdResponse = (UniRefund_LocationService_Districts_DistrictDto);

export type PutApiLocationServiceDistrictsByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Districts_DistrictUpdateDto;
};

export type PutApiLocationServiceDistrictsByIdResponse = (UniRefund_LocationService_Districts_DistrictDto);

export type DeleteApiLocationServiceDistrictsByIdData = {
    id: string;
};

export type DeleteApiLocationServiceDistrictsByIdResponse = (unknown);

export type GetApiLocationServiceNeighborhoodsData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceNeighborhoodsResponse = (PagedResultDto_NeighborhoodDto);

export type PostApiLocationServiceNeighborhoodsData = {
    requestBody?: UniRefund_LocationService_Neighborhoods_NeighborhoodCreateDto;
};

export type PostApiLocationServiceNeighborhoodsResponse = (UniRefund_LocationService_Neighborhoods_NeighborhoodDto);

export type GetApiLocationServiceNeighborhoodsGetListByDistrictByDistrictIdData = {
    districtId: string;
};

export type GetApiLocationServiceNeighborhoodsGetListByDistrictByDistrictIdResponse = (Array<UniRefund_LocationService_Neighborhoods_NeighborhoodDto>);

export type GetApiLocationServiceNeighborhoodsByIdData = {
    id: string;
};

export type GetApiLocationServiceNeighborhoodsByIdResponse = (UniRefund_LocationService_Neighborhoods_NeighborhoodDto);

export type PutApiLocationServiceNeighborhoodsByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Neighborhoods_NeighborhoodUpdateDto;
};

export type PutApiLocationServiceNeighborhoodsByIdResponse = (UniRefund_LocationService_Neighborhoods_NeighborhoodDto);

export type DeleteApiLocationServiceNeighborhoodsByIdData = {
    id: string;
};

export type DeleteApiLocationServiceNeighborhoodsByIdResponse = (unknown);

export type GetApiLocationServiceRegionsData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceRegionsResponse = (PagedResultDto_RegionDto);

export type PostApiLocationServiceRegionsData = {
    requestBody?: UniRefund_LocationService_Regions_RegionCreateDto;
};

export type PostApiLocationServiceRegionsResponse = (UniRefund_LocationService_Regions_RegionDto);

export type GetApiLocationServiceRegionsGetListByCountryByCountryIdData = {
    countryId: string;
};

export type GetApiLocationServiceRegionsGetListByCountryByCountryIdResponse = (Array<UniRefund_LocationService_Regions_RegionDto>);

export type GetApiLocationServiceRegionsByIdData = {
    id: string;
};

export type GetApiLocationServiceRegionsByIdResponse = (UniRefund_LocationService_Regions_RegionDto);

export type PutApiLocationServiceRegionsByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_Regions_RegionUpdateDto;
};

export type PutApiLocationServiceRegionsByIdResponse = (UniRefund_LocationService_Regions_RegionDto);

export type DeleteApiLocationServiceRegionsByIdData = {
    id: string;
};

export type DeleteApiLocationServiceRegionsByIdResponse = (unknown);

export type GetApiLocationServiceRegionsGetDefaultRegionIdByCountryIdData = {
    countryId: string;
};

export type GetApiLocationServiceRegionsGetDefaultRegionIdByCountryIdResponse = (string);

export type GetApiLocationServiceRegionalSettingsData = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiLocationServiceRegionalSettingsResponse = (PagedResultDto_RegionalSettingDto);

export type PostApiLocationServiceRegionalSettingsData = {
    requestBody?: UniRefund_LocationService_RegionalSettings_RegionalSettingCreateDto;
};

export type PostApiLocationServiceRegionalSettingsResponse = (UniRefund_LocationService_RegionalSettings_RegionalSettingDto);

export type GetApiLocationServiceRegionalSettingsByIdData = {
    id: string;
};

export type GetApiLocationServiceRegionalSettingsByIdResponse = (UniRefund_LocationService_RegionalSettings_RegionalSettingDto);

export type PutApiLocationServiceRegionalSettingsByIdData = {
    id: string;
    requestBody?: UniRefund_LocationService_RegionalSettings_RegionalSettingUpdateDto;
};

export type PutApiLocationServiceRegionalSettingsByIdResponse = (UniRefund_LocationService_RegionalSettings_RegionalSettingDto);

export type DeleteApiLocationServiceRegionalSettingsByIdData = {
    id: string;
};

export type DeleteApiLocationServiceRegionalSettingsByIdResponse = (unknown);