// This file is auto-generated by @hey-api/openapi-ts

export type PagedResultDto_AffiliationListResponseDto = {
    items?: Array<UniRefund_CRMService_Affiliations_AffiliationListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CustomDto = {
    items?: Array<UniRefund_CRMService_Customs_CustomDto> | null;
    totalCount?: number;
};

export type PagedResultDto_CustomListResponseDto = {
    items?: Array<UniRefund_CRMService_Customs_CustomListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_IndividualListResponseDto = {
    items?: Array<UniRefund_CRMService_Individuals_IndividualListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_MerchantListResponseDto = {
    items?: Array<UniRefund_CRMService_Merchants_MerchantListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RefundPointListResponseDto = {
    items?: Array<UniRefund_CRMService_RefundPoints_RefundPointListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_TaxFreeListResponseDto = {
    items?: Array<UniRefund_CRMService_TaxFrees_TaxFreeListResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_TaxOfficeDto = {
    items?: Array<UniRefund_CRMService_TaxOffices_TaxOfficeDto> | null;
    totalCount?: number;
};

export type PagedResultDto_TaxOfficeListResponseDto = {
    items?: Array<UniRefund_CRMService_TaxOffices_TaxOfficeListResponseDto> | null;
    totalCount?: number;
};

export type UniRefund_CRMService_Addresses_AddressDto = {
    id?: string;
    partyType: UniRefund_Shared_Contracts_Enums_PartyType;
    partyId: string;
    countryId: string;
    adminAreaLevel1Id: string;
    adminAreaLevel2Id: string;
    neighborhoodId: (string) | null;
    addressLine: (string) | null;
    postalCode?: (string) | null;
    type: UniRefund_CRMService_Addresses_AddressType;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
    isPrimary: boolean;
};

export type UniRefund_CRMService_Addresses_AddressType = 'UNKNOWN' | 'HOME' | 'WORK';

export type UniRefund_CRMService_Addresses_AddressUpSertDto = {
    addressId?: (string) | null;
    countryId?: (string) | null;
    adminAreaLevel1Id?: (string) | null;
    adminAreaLevel2Id?: (string) | null;
    neighborhoodId?: (string) | null;
    addressLine?: (string) | null;
    postalCode?: (string) | null;
    type?: UniRefund_CRMService_Addresses_AddressType;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
    isPrimary?: (boolean) | null;
};

export type UniRefund_CRMService_Addresses_CreateAddressDto = {
    partyType?: UniRefund_Shared_Contracts_Enums_PartyType;
    partyId?: string;
    countryId: string;
    adminAreaLevel1Id: string;
    adminAreaLevel2Id: string;
    neighborhoodId?: (string) | null;
    addressLine: (string) | null;
    postalCode?: (string) | null;
    type: UniRefund_CRMService_Addresses_AddressType;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
    isPrimary: boolean;
};

export type UniRefund_CRMService_AdminAreaLevel1_AdminAreaLevel1Dto = {
    id?: string;
    countryId: string;
    regionId?: (string) | null;
    name: (string) | null;
    shortName?: (string) | null;
    plateCode: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_AdminAreaLevel1_CreateAdminAreaLevel1Dto = {
    countryId: string;
    regionId?: (string) | null;
    name: (string) | null;
    shortName?: (string) | null;
    plateCode: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_AdminAreaLevel1_UpdateAdminAreaLevel1Dto = {
    countryId?: (string) | null;
    regionId?: (string) | null;
    name?: (string) | null;
    shortName?: (string) | null;
    plateCode?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_AdminAreaLevel2_AdminAreaLevel2Dto = {
    id?: string;
    adminAreaLevel1Id: string;
    name: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_AdminAreaLevel2_CreateAdminAreaLevel2Dto = {
    adminAreaLevel1Id: string;
    name: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_AdminAreaLevel2_UpdateAdminAreaLevel2Dto = {
    adminAreaLevel1Id?: (string) | null;
    name?: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_Affiliations_AffiliationDto = {
    id?: string;
    partyType: UniRefund_Shared_Contracts_Enums_PartyType;
    partyId: string;
    individualId: string;
    abpUserId?: (string) | null;
    abpRoleId: string;
    startDate?: (string) | null;
    endDate?: (string) | null;
    parentId?: (string) | null;
    isPrimary: boolean;
};

export type UniRefund_CRMService_Affiliations_AffiliationListResponseDto = {
    id?: string;
    name: (string) | null;
    roleName: (string) | null;
    individualId: string;
    abpRoleId: string;
    abpUserId?: (string) | null;
    readonly hasUserAccount?: (boolean) | null;
    startDate?: (string) | null;
    endDate?: (string) | null;
    isPrimary?: (boolean) | null;
};

export type UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto = {
    individualId: string;
    abpRoleId: string;
    startDate?: (string) | null;
    endDate?: (string) | null;
};

export type UniRefund_CRMService_Affiliations_UpdateAffiliationDto = {
    abpRoleId?: (string) | null;
    startDate?: (string) | null;
    endDate?: (string) | null;
};

export type UniRefund_CRMService_Countries_CountryDto = {
    id?: string;
    name?: (string) | null;
    shortName?: (string) | null;
    code2?: (string) | null;
    code3?: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_Countries_CreateCountryDto = {
    name: (string) | null;
    shortName?: (string) | null;
    code2: (string) | null;
    code3: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_Countries_UpdateCountryDto = {
    name?: (string) | null;
    shortName?: (string) | null;
    code2?: (string) | null;
    code3?: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_Customs_CreateCustomDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode?: UniRefund_CRMService_Customs_CustomTypeCode;
    telephone?: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address?: UniRefund_CRMService_Addresses_CreateAddressDto;
    email?: UniRefund_CRMService_Emails_EmailCreateDto;
};

export type UniRefund_CRMService_Customs_CustomDto = {
    id?: string;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
    name: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    vatNumber: (string) | null;
    externalIdentifier?: (string) | null;
    typeCode: UniRefund_CRMService_Customs_CustomTypeCode;
    status: UniRefund_CRMService_Customs_CustomStatus;
};

export type UniRefund_CRMService_Customs_CustomListResponseDto = {
    id?: string;
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    typeCode: UniRefund_CRMService_Customs_CustomTypeCode;
    status: UniRefund_CRMService_Customs_CustomStatus;
};

export type UniRefund_CRMService_Customs_CustomStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export type UniRefund_CRMService_Customs_CustomTypeCode = 'HEADQUARTER' | 'CUSTOM';

export type UniRefund_CRMService_Customs_UpdateCustomDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
};

export type UniRefund_CRMService_Emails_EmailCreateDto = {
    id?: (string) | null;
    emailAddress: (string) | null;
    isPrimary: boolean;
    type: UniRefund_CRMService_Emails_EmailType;
};

export type UniRefund_CRMService_Emails_EmailDto = {
    id?: string;
    emailAddress: (string) | null;
    type: UniRefund_CRMService_Emails_EmailType;
    isPrimary: boolean;
};

export type UniRefund_CRMService_Emails_EmailType = 'UNKNOWN' | 'PERSONAL' | 'WORK' | 'SCHOOL' | 'OTHER';

export type UniRefund_CRMService_Emails_EmailUpSertDto = {
    emailId?: (string) | null;
    emailAddress?: (string) | null;
    isPrimary?: (boolean) | null;
    type?: UniRefund_CRMService_Emails_EmailType;
};

export type UniRefund_CRMService_Individuals_CreateIndividualDto = {
    id?: string;
    firstname: (string) | null;
    lastname: (string) | null;
    gender: UniRefund_CRMService_Individuals_IndividualGender;
    identificationNumber?: (string) | null;
    birthDate?: (string) | null;
    notes?: (string) | null;
    telephone?: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address?: UniRefund_CRMService_Addresses_CreateAddressDto;
    email?: UniRefund_CRMService_Emails_EmailCreateDto;
    newUser?: UniRefund_CRMService_Individuals_NewUser;
};

export type UniRefund_CRMService_Individuals_IndividualDto = {
    id?: string;
    firstname: (string) | null;
    lastname: (string) | null;
    gender: UniRefund_CRMService_Individuals_IndividualGender;
    identificationNumber?: (string) | null;
    birthDate?: (string) | null;
    notes?: (string) | null;
    status?: UniRefund_CRMService_Individuals_IndividualStatus;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
};

export type UniRefund_CRMService_Individuals_IndividualGender = 'UNKNOWN' | 'MALE' | 'FEMALE' | 'OTHER';

export type UniRefund_CRMService_Individuals_IndividualListResponseDto = {
    id?: string;
    firstname: (string) | null;
    lastname: (string) | null;
    gender: UniRefund_CRMService_Individuals_IndividualGender;
    identificationNumber?: (string) | null;
};

export type UniRefund_CRMService_Individuals_IndividualStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED';

export type UniRefund_CRMService_Individuals_IndividualWithAbpUserDto = {
    individualId: string;
    fullname: (string) | null;
    abpUserId?: (string) | null;
};

export type UniRefund_CRMService_Individuals_NewUser = {
    username: (string) | null;
    password: (string) | null;
};

export type UniRefund_CRMService_Individuals_UpdateIndividualDto = {
    firstname?: (string) | null;
    lastname?: (string) | null;
    gender?: UniRefund_CRMService_Individuals_IndividualGender;
    identificationNumber?: (string) | null;
    birthDate?: (string) | null;
    notes?: (string) | null;
};

export type UniRefund_CRMService_Merchants_CreateMerchantDto = {
    chainCodeId?: (string) | null;
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode: UniRefund_CRMService_Merchants_MerchantTypeCode;
    isPersonalCompany: boolean;
    telephone: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address: UniRefund_CRMService_Addresses_CreateAddressDto;
    email: UniRefund_CRMService_Emails_EmailCreateDto;
};

export type UniRefund_CRMService_Merchants_MerchantDto = {
    id?: string;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
    chainCodeId?: (string) | null;
    name?: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    taxOfficeName?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    typeCode?: UniRefund_CRMService_Merchants_MerchantTypeCode;
    isPersonalCompany?: boolean;
    status?: UniRefund_CRMService_Merchants_MerchantStatus;
};

/**
 * Represents the detailed business information for a merchant within the tax-free system.
 * This DTO is used for transferring and displaying core merchant data.
 */
export type UniRefund_CRMService_Merchants_MerchantInfoForTagDto = {
    id?: string;
    /**
     * The **business name** of the merchant. This is the official trading name.
     */
    name: (string) | null;
    address: UniRefund_CRMService_Addresses_AddressDto;
    /**
     * A list of **product groups** that this merchant sells,
     * relevant for tax-free eligibility categorization.
     */
    productGroups: Array<UniRefund_SettingService_ProductGroups_ProductGroupDto> | null;
};

export type UniRefund_CRMService_Merchants_MerchantListResponseDto = {
    id?: string;
    chainCodeId?: (string) | null;
    name?: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    typeCode: UniRefund_CRMService_Merchants_MerchantTypeCode;
    isPersonalCompany: boolean;
    parentId?: (string) | null;
    parentName?: (string) | null;
    status: UniRefund_CRMService_Merchants_MerchantStatus;
};

export type UniRefund_CRMService_Merchants_MerchantStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export type UniRefund_CRMService_Merchants_MerchantSummaryRequestDto = {
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
};

export type UniRefund_CRMService_Merchants_MerchantSummaryResponseDto = {
    id?: string;
    name: (string) | null;
    vatNumber: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode: UniRefund_CRMService_Merchants_MerchantTypeCode;
    status: UniRefund_CRMService_Merchants_MerchantStatus;
};

export type UniRefund_CRMService_Merchants_MerchantTypeCode = 'HEADQUARTER' | 'STORE' | 'FRANCHISE';

export type UniRefund_CRMService_Merchants_UpdateMerchantDto = {
    chainCodeId?: (string) | null;
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode: UniRefund_CRMService_Merchants_MerchantTypeCode;
    isPersonalCompany?: (boolean) | null;
};

export type UniRefund_CRMService_Neighborhoods_CreateNeighborhoodDto = {
    adminAreaLevel2Id: string;
    name: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_Neighborhoods_NeighborhoodDto = {
    id?: string;
    adminAreaLevel2Id: string;
    name: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_Neighborhoods_UpdateNeighborhoodDto = {
    adminAreaLevel2Id?: (string) | null;
    name?: (string) | null;
    shortName?: (string) | null;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
};

export type UniRefund_CRMService_RefundPoints_CreateRefundPointDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode?: UniRefund_CRMService_RefundPoints_RefundPointTypeCode;
    telephone?: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address?: UniRefund_CRMService_Addresses_CreateAddressDto;
    email?: UniRefund_CRMService_Emails_EmailCreateDto;
};

export type UniRefund_CRMService_RefundPoints_RefundPointDetailForRefund = {
    id?: string;
    name?: (string) | null;
    fullAddress?: (string) | null;
};

export type UniRefund_CRMService_RefundPoints_RefundPointDto = {
    id?: string;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
    name?: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    taxOfficeName?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    status?: UniRefund_CRMService_RefundPoints_RefundPointStatus;
};

export type UniRefund_CRMService_RefundPoints_RefundPointListResponseDto = {
    id?: string;
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    status: UniRefund_CRMService_RefundPoints_RefundPointStatus;
    typeCode: UniRefund_CRMService_RefundPoints_RefundPointTypeCode;
};

export type UniRefund_CRMService_RefundPoints_RefundPointStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export type UniRefund_CRMService_RefundPoints_RefundPointTypeCode = 'HEADQUARTER' | 'REFUNDPOINT';

export type UniRefund_CRMService_RefundPoints_UpdateRefundPointDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    status?: UniRefund_CRMService_RefundPoints_RefundPointStatus;
};

export type UniRefund_CRMService_Regions_CreateRegionDto = {
    countryId: string;
    name: (string) | null;
    shortName?: (string) | null;
    code?: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_Regions_RegionDto = {
    id?: string;
    countryId: string;
    name: (string) | null;
    shortName?: (string) | null;
    code?: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_Regions_UpdateRegionDto = {
    countryId?: (string) | null;
    name?: (string) | null;
    shortName?: (string) | null;
    code?: (string) | null;
    placeId?: (string) | null;
};

export type UniRefund_CRMService_TaxFrees_CreateTaxFreeDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode: UniRefund_CRMService_TaxFrees_TaxFreeTypeCode;
    telephone: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address: UniRefund_CRMService_Addresses_CreateAddressDto;
    email: UniRefund_CRMService_Emails_EmailCreateDto;
};

export type UniRefund_CRMService_TaxFrees_TaxFreeDto = {
    id?: string;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
    name?: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    taxOfficeName?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    typeCode?: UniRefund_CRMService_TaxFrees_TaxFreeTypeCode;
    status?: UniRefund_CRMService_TaxFrees_TaxFreeStatus;
};

export type UniRefund_CRMService_TaxFrees_TaxFreeListResponseDto = {
    id?: string;
    name: (string) | null;
    vatNumber: (string) | null;
    externalIdentifier: (string) | null;
    parentId?: (string) | null;
    parentName: (string) | null;
    typeCode: UniRefund_CRMService_TaxFrees_TaxFreeTypeCode;
    status: UniRefund_CRMService_TaxFrees_TaxFreeStatus;
};

export type UniRefund_CRMService_TaxFrees_TaxFreeStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export type UniRefund_CRMService_TaxFrees_TaxFreeTypeCode = 'HEADQUARTER' | 'TAXFREE';

export type UniRefund_CRMService_TaxFrees_UpdateTaxFreeDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    taxOfficeId?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    status: UniRefund_CRMService_TaxFrees_TaxFreeStatus;
};

export type UniRefund_CRMService_TaxOffices_CreateTaxOfficeDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    typeCode: UniRefund_CRMService_TaxOffices_TaxOfficeTypeCode;
    telephone: UniRefund_CRMService_Telephones_TelephoneCreateDto;
    address: UniRefund_CRMService_Addresses_CreateAddressDto;
    email: UniRefund_CRMService_Emails_EmailCreateDto;
};

export type UniRefund_CRMService_TaxOffices_TaxOfficeDto = {
    id?: string;
    telephone?: UniRefund_CRMService_Telephones_TelephoneDto;
    address?: UniRefund_CRMService_Addresses_AddressDto;
    email?: UniRefund_CRMService_Emails_EmailDto;
    name?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    typeCode?: UniRefund_CRMService_TaxOffices_TaxOfficeTypeCode;
};

export type UniRefund_CRMService_TaxOffices_TaxOfficeListResponseDto = {
    id?: string;
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
    parentName?: (string) | null;
    typeCode: UniRefund_CRMService_TaxOffices_TaxOfficeTypeCode;
    status: UniRefund_CRMService_TaxOffices_TaxOfficeStatus;
};

export type UniRefund_CRMService_TaxOffices_TaxOfficeStatus = 'DRAFT' | 'WAITINGAPPROVAL' | 'APPROVED' | 'REJECTED' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export type UniRefund_CRMService_TaxOffices_TaxOfficeTypeCode = 'HEADQUARTER' | 'TAXOFFICE';

export type UniRefund_CRMService_TaxOffices_UpdateTaxOfficeDto = {
    name: (string) | null;
    vatNumber?: (string) | null;
    externalIdentifier?: (string) | null;
    parentId?: (string) | null;
};

export type UniRefund_CRMService_Telephones_TelephoneCreateDto = {
    ituCountryCode?: (string) | null;
    areaCode?: (string) | null;
    localNumber?: (string) | null;
    isPrimary?: boolean;
    type?: UniRefund_Shared_ContactInfo_Enums_TelephoneType;
};

export type UniRefund_CRMService_Telephones_TelephoneDto = {
    id: string;
    ituCountryCode?: (string) | null;
    areaCode?: (string) | null;
    localNumber: (string) | null;
    normalizedPhoneNumber?: (string) | null;
    isPrimary: boolean;
    type: UniRefund_Shared_ContactInfo_Enums_TelephoneType;
    isConfirmed?: (boolean) | null;
};

export type UniRefund_CRMService_Telephones_TelephoneUpsertDto = {
    telephoneId?: (string) | null;
    ituCountryCode?: (string) | null;
    areaCode?: (string) | null;
    localNumber?: (string) | null;
    isPrimary?: (boolean) | null;
    type?: UniRefund_Shared_ContactInfo_Enums_TelephoneType;
};

export type UniRefund_CRMService_UserAffiliations_SetPrimaryAffiliationDto = {
    partyId?: string;
};

export type UniRefund_CRMService_UserAffiliations_UserAffiliationDto = {
    affiliationId?: string;
    partyId?: string;
    partyType?: UniRefund_Shared_Contracts_Enums_PartyType;
    partyName?: (string) | null;
    vatNumber?: (string) | null;
    identificationNumber?: (string) | null;
    isPrimary?: boolean;
    parentId?: (string) | null;
};

export type UniRefund_SettingService_ProductGroupMerchants_CreateProductGroupMerchantBaseDto = {
    productGroupId: string;
    isDefault?: boolean;
};

export type UniRefund_SettingService_ProductGroupMerchants_CreateProductGroupMerchantDto = {
    productGroupId: string;
    isDefault?: boolean;
    merchantId?: string;
};

export type UniRefund_SettingService_ProductGroupMerchants_ProductGroupMerchantRelationDto = {
    productGroupName: string;
    isDefault: boolean;
    isActive: boolean;
    isAssign: boolean;
    productGroupId: string;
    vatRate: number;
    vatId: string;
};

export type UniRefund_SettingService_ProductGroups_CompanyTypeCode = 'GOVERNMENT' | 'TAXFREE' | 'CUSTOMS' | 'REFUNDPOINT' | 'MERCHANT' | 'EXCHANGE' | 'TOURGUIDE';

/**
 * Represents a group of products with common characteristics, used for categorization and tax purposes.
 */
export type UniRefund_SettingService_ProductGroups_ProductGroupDto = {
    id?: string;
    /**
     * The unique article code for the product group. This field is **required**.
     */
    articleCode: string;
    /**
     * The name of the product group (e.g., "Electronics", "Apparel"). This field is **required**.
     */
    name: string;
    unitCode: UniRefund_SettingService_ProductGroups_UnitTypeCode;
    companyType: UniRefund_SettingService_ProductGroups_CompanyTypeCode;
    /**
     * The unique identifier for the VAT (Value Added Tax) category applicable to this product group.
     */
    vatId?: string;
    /**
     * The percentage of VAT applied to products in this group, if applicable.
     */
    vatPercent?: (number) | null;
    /**
     * Indicates whether the product group is currently active. This field is **required**.
     */
    active: boolean;
    /**
     * Indicates whether the product group consists of food items. This field is **required**.
     */
    food: boolean;
};

export type UniRefund_SettingService_ProductGroups_UnitTypeCode = 'QNT' | 'BAG' | 'BOX';

export type UniRefund_Shared_ContactInfo_Enums_TelephoneType = 'UNKNOWN' | 'HOME' | 'WORK' | 'MOBILE' | 'FAX' | 'OTHER';

export type UniRefund_Shared_Contracts_Enums_PartyType = 'INDIVIDUAL' | 'MERCHANT' | 'REFUNDPOINT' | 'CUSTOM' | 'TAXFREE' | 'TAXOFFICE' | 'TOURGUIDE' | 'TRAVELLER';

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type PostApiCrmServiceAdminAreaLevel1Data = {
    requestBody?: UniRefund_CRMService_AdminAreaLevel1_CreateAdminAreaLevel1Dto;
};

export type PostApiCrmServiceAdminAreaLevel1Response = (string);

export type DeleteApiCrmServiceAdminAreaLevel1ByIdData = {
    id: string;
};

export type DeleteApiCrmServiceAdminAreaLevel1ByIdResponse = (unknown);

export type GetApiCrmServiceAdminAreaLevel1ByIdData = {
    id: string;
};

export type GetApiCrmServiceAdminAreaLevel1ByIdResponse = (UniRefund_CRMService_AdminAreaLevel1_AdminAreaLevel1Dto);

export type PutApiCrmServiceAdminAreaLevel1ByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_AdminAreaLevel1_UpdateAdminAreaLevel1Dto;
};

export type PutApiCrmServiceAdminAreaLevel1ByIdResponse = (UniRefund_CRMService_AdminAreaLevel1_AdminAreaLevel1Dto);

export type GetApiCrmServiceAdminAreaLevel1ByCountryByCountryIdData = {
    countryId: string;
};

export type GetApiCrmServiceAdminAreaLevel1ByCountryByCountryIdResponse = (Array<UniRefund_CRMService_AdminAreaLevel1_AdminAreaLevel1Dto>);

export type PostApiCrmServiceAdminAreaLevel2Data = {
    requestBody?: UniRefund_CRMService_AdminAreaLevel2_CreateAdminAreaLevel2Dto;
};

export type PostApiCrmServiceAdminAreaLevel2Response = (string);

export type DeleteApiCrmServiceAdminAreaLevel2ByIdData = {
    id: string;
};

export type DeleteApiCrmServiceAdminAreaLevel2ByIdResponse = (unknown);

export type GetApiCrmServiceAdminAreaLevel2ByIdData = {
    id: string;
};

export type GetApiCrmServiceAdminAreaLevel2ByIdResponse = (UniRefund_CRMService_AdminAreaLevel2_AdminAreaLevel2Dto);

export type PutApiCrmServiceAdminAreaLevel2ByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_AdminAreaLevel2_UpdateAdminAreaLevel2Dto;
};

export type PutApiCrmServiceAdminAreaLevel2ByIdResponse = (UniRefund_CRMService_AdminAreaLevel2_AdminAreaLevel2Dto);

export type GetApiCrmServiceAdminAreaLevel2ByAdminAreaLevel1ByAdminAreaLevel1IdData = {
    adminAreaLevel1Id: string;
};

export type GetApiCrmServiceAdminAreaLevel2ByAdminAreaLevel1ByAdminAreaLevel1IdResponse = (Array<UniRefund_CRMService_AdminAreaLevel2_AdminAreaLevel2Dto>);

export type PostApiCrmServiceCountriesData = {
    requestBody?: UniRefund_CRMService_Countries_CreateCountryDto;
};

export type PostApiCrmServiceCountriesResponse = (string);

export type GetApiCrmServiceCountriesResponse = (Array<UniRefund_CRMService_Countries_CountryDto>);

export type DeleteApiCrmServiceCountriesByIdData = {
    id: string;
};

export type DeleteApiCrmServiceCountriesByIdResponse = (unknown);

export type GetApiCrmServiceCountriesByIdData = {
    id: string;
};

export type GetApiCrmServiceCountriesByIdResponse = (UniRefund_CRMService_Countries_CountryDto);

export type PutApiCrmServiceCountriesByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Countries_UpdateCountryDto;
};

export type PutApiCrmServiceCountriesByIdResponse = (UniRefund_CRMService_Countries_CountryDto);

export type PostApiCrmServiceCustomsData = {
    requestBody?: UniRefund_CRMService_Customs_CreateCustomDto;
};

export type PostApiCrmServiceCustomsResponse = (string);

export type GetApiCrmServiceCustomsData = {
    customIds?: Array<(string)>;
    externalIdentifier?: string;
    maxResultCount?: number;
    name?: string;
    parentId?: string;
    skipCount?: number;
    sorting?: string;
    statuses?: Array<UniRefund_CRMService_RefundPoints_RefundPointStatus>;
    typeCodes?: Array<UniRefund_CRMService_Customs_CustomTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceCustomsResponse = (PagedResultDto_CustomListResponseDto);

export type PostApiCrmServiceCustomsByIdAffiliationsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto;
};

export type PostApiCrmServiceCustomsByIdAffiliationsResponse = (string);

export type GetApiCrmServiceCustomsByIdAffiliationsData = {
    email?: string;
    id: string;
    maxResultCount?: number;
    name?: string;
    roleName?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceCustomsByIdAffiliationsResponse = (PagedResultDto_AffiliationListResponseDto);

export type DeleteApiCrmServiceCustomsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceCustomsByIdResponse = (unknown);

export type GetApiCrmServiceCustomsByIdData = {
    id: string;
};

export type GetApiCrmServiceCustomsByIdResponse = (UniRefund_CRMService_Customs_CustomDto);

export type PutApiCrmServiceCustomsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Customs_UpdateCustomDto;
};

export type PutApiCrmServiceCustomsByIdResponse = (UniRefund_CRMService_Customs_CustomDto);

export type DeleteApiCrmServiceCustomsByCustomIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    customId: string;
};

export type DeleteApiCrmServiceCustomsByCustomIdAffiliationsByAffiliationIdResponse = (unknown);

export type PutApiCrmServiceCustomsByCustomIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    customId: string;
    requestBody?: UniRefund_CRMService_Affiliations_UpdateAffiliationDto;
};

export type PutApiCrmServiceCustomsByCustomIdAffiliationsByAffiliationIdResponse = (UniRefund_CRMService_Affiliations_AffiliationDto);

export type GetApiCrmServiceCustomsByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceCustomsByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type PutApiCrmServiceCustomsByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceCustomsByIdAddressesResponse = (unknown);

export type GetApiCrmServiceCustomsByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceCustomsByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceCustomsByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceCustomsByIdEmailsResponse = (unknown);

export type GetApiCrmServiceCustomsByIdSubCustomsData = {
    id: string;
};

export type GetApiCrmServiceCustomsByIdSubCustomsResponse = (PagedResultDto_CustomDto);

export type GetApiCrmServiceCustomsByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceCustomsByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceCustomsByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceCustomsByIdTelephonesResponse = (unknown);

export type PostApiCrmServiceIndividualsData = {
    requestBody?: UniRefund_CRMService_Individuals_CreateIndividualDto;
};

export type PostApiCrmServiceIndividualsResponse = (string);

export type GetApiCrmServiceIndividualsData = {
    email?: string;
    identificationNumber?: string;
    maxResultCount?: number;
    name?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceIndividualsResponse = (PagedResultDto_IndividualListResponseDto);

export type GetApiCrmServiceIndividualsByIdData = {
    id: string;
};

export type GetApiCrmServiceIndividualsByIdResponse = (UniRefund_CRMService_Individuals_IndividualDto);

export type PutApiCrmServiceIndividualsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Individuals_UpdateIndividualDto;
};

export type PutApiCrmServiceIndividualsByIdResponse = (UniRefund_CRMService_Individuals_IndividualDto);

export type DeleteApiCrmServiceIndividualsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceIndividualsByIdResponse = (unknown);

export type PutApiCrmServiceIndividualsByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceIndividualsByIdTelephonesResponse = (unknown);

export type GetApiCrmServiceIndividualsByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceIndividualsByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceIndividualsByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceIndividualsByIdEmailsResponse = (unknown);

export type GetApiCrmServiceIndividualsByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceIndividualsByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceIndividualsByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceIndividualsByIdAddressesResponse = (unknown);

export type GetApiCrmServiceIndividualsByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceIndividualsByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type GetApiCrmServiceIndividualsByEmailData = {
    email?: string;
};

export type GetApiCrmServiceIndividualsByEmailResponse = (Array<UniRefund_CRMService_Individuals_IndividualWithAbpUserDto>);

export type GetApiCrmServiceMerchantsByIdData = {
    id: string;
};

export type GetApiCrmServiceMerchantsByIdResponse = (UniRefund_CRMService_Merchants_MerchantDto);

export type PutApiCrmServiceMerchantsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Merchants_UpdateMerchantDto;
};

export type PutApiCrmServiceMerchantsByIdResponse = (UniRefund_CRMService_Merchants_MerchantDto);

export type DeleteApiCrmServiceMerchantsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceMerchantsByIdResponse = (unknown);

export type GetApiCrmServiceMerchantsByIdSubMerchantsData = {
    chainCodeId?: string;
    externalIdentifier?: string;
    id: string;
    maxResultCount?: number;
    merchantIds?: Array<(string)>;
    name?: string;
    parentId?: string;
    productGroupIds?: Array<(string)>;
    skipCount?: number;
    sorting?: string;
    statusCodes?: Array<UniRefund_CRMService_Merchants_MerchantStatus>;
    typeCodes?: Array<UniRefund_CRMService_Merchants_MerchantTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceMerchantsByIdSubMerchantsResponse = (PagedResultDto_MerchantListResponseDto);

export type GetApiCrmServiceMerchantsByIdAffiliationsData = {
    email?: string;
    id: string;
    maxResultCount?: number;
    name?: string;
    roleName?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceMerchantsByIdAffiliationsResponse = (PagedResultDto_AffiliationListResponseDto);

export type PostApiCrmServiceMerchantsByIdAffiliationsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto;
};

export type PostApiCrmServiceMerchantsByIdAffiliationsResponse = (string);

export type DeleteApiCrmServiceMerchantsByMerchantIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    merchantId: string;
};

export type DeleteApiCrmServiceMerchantsByMerchantIdAffiliationsByAffiliationIdResponse = (unknown);

export type PutApiCrmServiceMerchantsByMerchantIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    merchantId: string;
    requestBody?: UniRefund_CRMService_Affiliations_UpdateAffiliationDto;
};

export type PutApiCrmServiceMerchantsByMerchantIdAffiliationsByAffiliationIdResponse = (UniRefund_CRMService_Affiliations_AffiliationDto);

export type PostApiCrmServiceMerchantsBulkProductGroupMerchantsData = {
    requestBody?: Array<UniRefund_SettingService_ProductGroupMerchants_CreateProductGroupMerchantDto>;
};

export type PostApiCrmServiceMerchantsBulkProductGroupMerchantsResponse = (unknown);

export type GetApiCrmServiceMerchantsByIdProductGroupData = {
    id: string;
};

export type GetApiCrmServiceMerchantsByIdProductGroupResponse = (Array<UniRefund_SettingService_ProductGroupMerchants_ProductGroupMerchantRelationDto>);

export type PostApiCrmServiceMerchantsByIdProductGroupsData = {
    id: string;
    requestBody?: Array<UniRefund_SettingService_ProductGroupMerchants_CreateProductGroupMerchantBaseDto>;
};

export type PostApiCrmServiceMerchantsByIdProductGroupsResponse = (unknown);

export type DeleteApiCrmServiceMerchantsByIdProductGroupsData = {
    id: string;
    requestBody?: Array<(string)>;
};

export type DeleteApiCrmServiceMerchantsByIdProductGroupsResponse = (unknown);

export type PostApiCrmServiceMerchantsByMerchantIdProductGroupByProductGroupIdDefaultData = {
    merchantId: string;
    productGroupId: string;
};

export type PostApiCrmServiceMerchantsByMerchantIdProductGroupByProductGroupIdDefaultResponse = (unknown);

export type PostApiCrmServiceMerchantsData = {
    requestBody?: UniRefund_CRMService_Merchants_CreateMerchantDto;
};

export type PostApiCrmServiceMerchantsResponse = (string);

export type GetApiCrmServiceMerchantsData = {
    chainCodeId?: string;
    externalIdentifier?: string;
    maxResultCount?: number;
    merchantIds?: Array<(string)>;
    name?: string;
    parentId?: string;
    productGroupIds?: Array<(string)>;
    skipCount?: number;
    sorting?: string;
    statusCodes?: Array<UniRefund_CRMService_Merchants_MerchantStatus>;
    typeCodes?: Array<UniRefund_CRMService_Merchants_MerchantTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceMerchantsResponse = (PagedResultDto_MerchantListResponseDto);

export type PutApiCrmServiceMerchantsByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceMerchantsByIdTelephonesResponse = (unknown);

export type GetApiCrmServiceMerchantsByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceMerchantsByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceMerchantsByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceMerchantsByIdEmailsResponse = (unknown);

export type GetApiCrmServiceMerchantsByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceMerchantsByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceMerchantsByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceMerchantsByIdAddressesResponse = (unknown);

export type GetApiCrmServiceMerchantsByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceMerchantsByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type PostApiCrmServiceNeighborhoodsData = {
    requestBody?: UniRefund_CRMService_Neighborhoods_CreateNeighborhoodDto;
};

export type PostApiCrmServiceNeighborhoodsResponse = (string);

export type DeleteApiCrmServiceNeighborhoodsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceNeighborhoodsByIdResponse = (unknown);

export type PutApiCrmServiceNeighborhoodsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Neighborhoods_UpdateNeighborhoodDto;
};

export type PutApiCrmServiceNeighborhoodsByIdResponse = (UniRefund_CRMService_Neighborhoods_NeighborhoodDto);

export type GetApiCrmServiceNeighborhoodsByAdminAreaLevel2ByAdminAreaLevel2IdData = {
    adminAreaLevel2Id: string;
};

export type GetApiCrmServiceNeighborhoodsByAdminAreaLevel2ByAdminAreaLevel2IdResponse = (Array<UniRefund_CRMService_Neighborhoods_NeighborhoodDto>);

export type PostApiCrmServiceRefundPointsData = {
    requestBody?: UniRefund_CRMService_RefundPoints_CreateRefundPointDto;
};

export type PostApiCrmServiceRefundPointsResponse = (string);

export type GetApiCrmServiceRefundPointsData = {
    externalIdentifier?: string;
    maxResultCount?: number;
    name?: string;
    parentId?: string;
    refundPointIds?: Array<(string)>;
    skipCount?: number;
    sorting?: string;
    statuses?: Array<UniRefund_CRMService_RefundPoints_RefundPointStatus>;
    typeCodes?: Array<UniRefund_CRMService_RefundPoints_RefundPointTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceRefundPointsResponse = (PagedResultDto_RefundPointListResponseDto);

export type PostApiCrmServiceRefundPointsByIdAffiliationsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto;
};

export type PostApiCrmServiceRefundPointsByIdAffiliationsResponse = (string);

export type GetApiCrmServiceRefundPointsByIdAffiliationsData = {
    email?: string;
    id: string;
    maxResultCount?: number;
    name?: string;
    roleName?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceRefundPointsByIdAffiliationsResponse = (PagedResultDto_AffiliationListResponseDto);

export type DeleteApiCrmServiceRefundPointsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceRefundPointsByIdResponse = (unknown);

export type GetApiCrmServiceRefundPointsByIdData = {
    id: string;
};

export type GetApiCrmServiceRefundPointsByIdResponse = (UniRefund_CRMService_RefundPoints_RefundPointDto);

export type PutApiCrmServiceRefundPointsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_RefundPoints_UpdateRefundPointDto;
};

export type PutApiCrmServiceRefundPointsByIdResponse = (UniRefund_CRMService_RefundPoints_RefundPointDto);

export type DeleteApiCrmServiceRefundPointsByRefundPointIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    refundPointId: string;
};

export type DeleteApiCrmServiceRefundPointsByRefundPointIdAffiliationsByAffiliationIdResponse = (unknown);

export type PutApiCrmServiceRefundPointsByRefundPointIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    refundPointId: string;
    requestBody?: UniRefund_CRMService_Affiliations_UpdateAffiliationDto;
};

export type PutApiCrmServiceRefundPointsByRefundPointIdAffiliationsByAffiliationIdResponse = (UniRefund_CRMService_Affiliations_AffiliationDto);

export type GetApiCrmServiceRefundPointsByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceRefundPointsByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type PutApiCrmServiceRefundPointsByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceRefundPointsByIdAddressesResponse = (unknown);

export type GetApiCrmServiceRefundPointsByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceRefundPointsByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceRefundPointsByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceRefundPointsByIdEmailsResponse = (unknown);

export type GetApiCrmServiceRefundPointsByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceRefundPointsByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceRefundPointsByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceRefundPointsByIdTelephonesResponse = (unknown);

export type PostApiCrmServiceRegionsData = {
    requestBody?: UniRefund_CRMService_Regions_CreateRegionDto;
};

export type PostApiCrmServiceRegionsResponse = (string);

export type DeleteApiCrmServiceRegionsByIdData = {
    id: string;
};

export type DeleteApiCrmServiceRegionsByIdResponse = (unknown);

export type GetApiCrmServiceRegionsByIdData = {
    id: string;
};

export type GetApiCrmServiceRegionsByIdResponse = (UniRefund_CRMService_Regions_RegionDto);

export type PutApiCrmServiceRegionsByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_Regions_UpdateRegionDto;
};

export type PutApiCrmServiceRegionsByIdResponse = (UniRefund_CRMService_Regions_RegionDto);

export type GetApiCrmServiceRegionsByCountryByCountryIdData = {
    countryId: string;
};

export type GetApiCrmServiceRegionsByCountryByCountryIdResponse = (Array<UniRefund_CRMService_Regions_RegionDto>);

export type PostApiCrmServiceTaxFreesData = {
    requestBody?: UniRefund_CRMService_TaxFrees_CreateTaxFreeDto;
};

export type PostApiCrmServiceTaxFreesResponse = (string);

export type GetApiCrmServiceTaxFreesData = {
    externalIdentifier?: string;
    maxResultCount?: number;
    name?: string;
    parentId?: string;
    skipCount?: number;
    sorting?: string;
    statuses?: Array<UniRefund_CRMService_TaxFrees_TaxFreeStatus>;
    taxFreeIds?: Array<(string)>;
    typeCodes?: Array<UniRefund_CRMService_TaxFrees_TaxFreeTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceTaxFreesResponse = (PagedResultDto_TaxFreeListResponseDto);

export type PostApiCrmServiceTaxFreesByIdAffiliationsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto;
};

export type PostApiCrmServiceTaxFreesByIdAffiliationsResponse = (string);

export type GetApiCrmServiceTaxFreesByIdAffiliationsData = {
    email?: string;
    id: string;
    maxResultCount?: number;
    name?: string;
    roleName?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceTaxFreesByIdAffiliationsResponse = (PagedResultDto_AffiliationListResponseDto);

export type DeleteApiCrmServiceTaxFreesByIdData = {
    id: string;
};

export type DeleteApiCrmServiceTaxFreesByIdResponse = (unknown);

export type GetApiCrmServiceTaxFreesByIdData = {
    id: string;
};

export type GetApiCrmServiceTaxFreesByIdResponse = (UniRefund_CRMService_TaxFrees_TaxFreeDto);

export type PutApiCrmServiceTaxFreesByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_TaxFrees_UpdateTaxFreeDto;
};

export type PutApiCrmServiceTaxFreesByIdResponse = (UniRefund_CRMService_TaxFrees_TaxFreeDto);

export type DeleteApiCrmServiceTaxFreesByTaxFreeIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    taxFreeId: string;
};

export type DeleteApiCrmServiceTaxFreesByTaxFreeIdAffiliationsByAffiliationIdResponse = (unknown);

export type PutApiCrmServiceTaxFreesByTaxFreeIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    requestBody?: UniRefund_CRMService_Affiliations_UpdateAffiliationDto;
    taxFreeId: string;
};

export type PutApiCrmServiceTaxFreesByTaxFreeIdAffiliationsByAffiliationIdResponse = (UniRefund_CRMService_Affiliations_AffiliationDto);

export type GetApiCrmServiceTaxFreesByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceTaxFreesByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type PutApiCrmServiceTaxFreesByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceTaxFreesByIdAddressesResponse = (unknown);

export type GetApiCrmServiceTaxFreesByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceTaxFreesByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceTaxFreesByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceTaxFreesByIdEmailsResponse = (unknown);

export type GetApiCrmServiceTaxFreesByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceTaxFreesByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceTaxFreesByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceTaxFreesByIdTelephonesResponse = (unknown);

export type PostApiCrmServiceTaxOfficesData = {
    requestBody?: UniRefund_CRMService_TaxOffices_CreateTaxOfficeDto;
};

export type PostApiCrmServiceTaxOfficesResponse = (string);

export type GetApiCrmServiceTaxOfficesData = {
    externalIdentifier?: string;
    maxResultCount?: number;
    name?: string;
    parentId?: string;
    skipCount?: number;
    sorting?: string;
    statuses?: Array<UniRefund_CRMService_TaxOffices_TaxOfficeStatus>;
    taxOfficeIds?: Array<(string)>;
    typeCodes?: Array<UniRefund_CRMService_TaxOffices_TaxOfficeTypeCode>;
    vatNumber?: string;
};

export type GetApiCrmServiceTaxOfficesResponse = (PagedResultDto_TaxOfficeListResponseDto);

export type PostApiCrmServiceTaxOfficesByIdAffiliationsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Affiliations_CreatePartyAffiliationDto;
};

export type PostApiCrmServiceTaxOfficesByIdAffiliationsResponse = (string);

export type GetApiCrmServiceTaxOfficesByIdAffiliationsData = {
    email?: string;
    id: string;
    maxResultCount?: number;
    name?: string;
    roleName?: string;
    skipCount?: number;
    sorting?: string;
    telephone?: string;
};

export type GetApiCrmServiceTaxOfficesByIdAffiliationsResponse = (PagedResultDto_AffiliationListResponseDto);

export type DeleteApiCrmServiceTaxOfficesByIdData = {
    id: string;
};

export type DeleteApiCrmServiceTaxOfficesByIdResponse = (unknown);

export type GetApiCrmServiceTaxOfficesByIdData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdResponse = (UniRefund_CRMService_TaxOffices_TaxOfficeDto);

export type PutApiCrmServiceTaxOfficesByIdData = {
    id: string;
    requestBody?: UniRefund_CRMService_TaxOffices_UpdateTaxOfficeDto;
};

export type PutApiCrmServiceTaxOfficesByIdResponse = (UniRefund_CRMService_TaxOffices_TaxOfficeDto);

export type DeleteApiCrmServiceTaxOfficesByTaxOfficeIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    taxOfficeId: string;
};

export type DeleteApiCrmServiceTaxOfficesByTaxOfficeIdAffiliationsByAffiliationIdResponse = (unknown);

export type PutApiCrmServiceTaxOfficesByTaxOfficeIdAffiliationsByAffiliationIdData = {
    affiliationId: string;
    requestBody?: UniRefund_CRMService_Affiliations_UpdateAffiliationDto;
    taxOfficeId: string;
};

export type PutApiCrmServiceTaxOfficesByTaxOfficeIdAffiliationsByAffiliationIdResponse = (UniRefund_CRMService_Affiliations_AffiliationDto);

export type GetApiCrmServiceTaxOfficesByIdExistsData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdExistsResponse = (boolean);

export type GetApiCrmServiceTaxOfficesByIdAddressesData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdAddressesResponse = (Array<UniRefund_CRMService_Addresses_AddressDto>);

export type PutApiCrmServiceTaxOfficesByIdAddressesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Addresses_AddressUpSertDto;
};

export type PutApiCrmServiceTaxOfficesByIdAddressesResponse = (unknown);

export type GetApiCrmServiceTaxOfficesByIdEmailsData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdEmailsResponse = (Array<UniRefund_CRMService_Emails_EmailDto>);

export type PutApiCrmServiceTaxOfficesByIdEmailsData = {
    id: string;
    requestBody?: UniRefund_CRMService_Emails_EmailUpSertDto;
};

export type PutApiCrmServiceTaxOfficesByIdEmailsResponse = (unknown);

export type GetApiCrmServiceTaxOfficesByIdSubTaxOfficesData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdSubTaxOfficesResponse = (PagedResultDto_TaxOfficeDto);

export type GetApiCrmServiceTaxOfficesByIdTelephonesData = {
    id: string;
};

export type GetApiCrmServiceTaxOfficesByIdTelephonesResponse = (Array<UniRefund_CRMService_Telephones_TelephoneDto>);

export type PutApiCrmServiceTaxOfficesByIdTelephonesData = {
    id: string;
    requestBody?: UniRefund_CRMService_Telephones_TelephoneUpsertDto;
};

export type PutApiCrmServiceTaxOfficesByIdTelephonesResponse = (unknown);

export type GetApiCrmServiceUserAffiliationsResponse = (Array<UniRefund_CRMService_UserAffiliations_UserAffiliationDto>);

export type PostApiCrmServiceUserAffiliationsSetActiveAffiliationData = {
    requestBody?: UniRefund_CRMService_UserAffiliations_SetPrimaryAffiliationDto;
};

export type PostApiCrmServiceUserAffiliationsSetActiveAffiliationResponse = (unknown);