// This file is auto-generated by @hey-api/openapi-ts

export type PagedResultDto_ContractHeaderDetailForMerchantDto = {
    items?: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderDetailForMerchantDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ContractHeaderDetailForRefundPointDto = {
    items?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderDetailForRefundPointDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ContractHeaderForMerchantDto = {
    items?: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ContractHeaderForRefundPointDto = {
    items?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ContractSettingDto = {
    items?: Array<UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ContractStoreDetailedDto = {
    items?: Array<UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreDetailedDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RebateTableHeaderListDto = {
    items?: Array<UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderListDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RefundFeeHeaderListDto = {
    items?: Array<UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderListDto> | null;
    totalCount?: number;
};

export type PagedResultDto_RefundTableHeaderListDto = {
    items?: Array<UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderListDto> | null;
    totalCount?: number;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaderRefundTableHeaders_ContractHeaderRefundTableHeaderCreateAndUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    refundTableHeaderId: string;
    validFrom: string;
    validTo?: (string) | null;
    isDefault?: boolean;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaderRefundTableHeaders_ContractHeaderRefundTableHeaderInformationDto = {
    name: string;
    id: string;
    validFrom: string;
    validTo?: (string) | null;
    isDefault: boolean;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderDetailForMerchantDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    contractTypeIdentifier: string;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    merchantBasicInformationDto?: UniRefund_CRMService_Merchants_MerchantBasicInformationDto;
    isDraft: boolean;
    isEnabled: boolean;
    isActive: boolean;
    validFrom: string;
    validTo?: (string) | null;
    contractType: UniRefund_ContractService_Enums_ContractType;
    addressCommonDataId: string;
    refundTableHeaders: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaderRefundTableHeaders_ContractHeaderRefundTableHeaderInformationDto>;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    validFrom: string;
    validTo?: (string) | null;
    addressCommonDataId: string;
    refundTableHeaders: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaderRefundTableHeaders_ContractHeaderRefundTableHeaderCreateAndUpdateDto>;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    contractTypeIdentifier: string;
    isDraft: boolean;
    isEnabled: boolean;
    isActive: boolean;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    contractType: UniRefund_ContractService_Enums_ContractType;
    validFrom: string;
    validTo?: (string) | null;
    addressCommonDataId: string;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    validFrom: string;
    validTo?: (string) | null;
    addressCommonDataId: string;
    refundTableHeaders?: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaderRefundTableHeaders_ContractHeaderRefundTableHeaderCreateAndUpdateDto> | null;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderInformationForVATStatementDto = {
    merchantId?: string;
    contractHeaderId?: string;
    billingPeriod?: UniRefund_ContractService_Enums_InvoicingFrequency;
    termOfPayment?: number;
    isFactoring?: boolean;
    deliveryMethod?: UniRefund_ContractService_Enums_InvoiceChannel;
};

/**
 * Represents a request to ensure that a merchant has an active contract header.
 */
export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_EnsureHasEnabledContractHeaderRequestDto = {
    /**
     * Gets or sets the ID of the merchant to check.
     */
    merchantId: string;
    /**
     * Gets or sets a list of tuples containing the invoice date and amount to verify against the contract headers.
     */
    invoices: Array<UniRefund_ContractService_ContractsForMerchant_ContractHeaders_EnsureHasEnabledContractHeaderRequestItemDto>;
};

/**
 * Represents an item in the request to ensure that a merchant has an active contract header.
 */
export type UniRefund_ContractService_ContractsForMerchant_ContractHeaders_EnsureHasEnabledContractHeaderRequestItemDto = {
    /**
     * Gets or sets the date of the invoice.
     */
    invoiceDate: string;
    /**
     * Gets or sets the amount of the invoice.
     */
    invoiceAmount: number;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    referenceNumber: number;
    invoicingFrequency: UniRefund_ContractService_Enums_InvoicingFrequency;
    termOfPayment: number;
    deliveryFee?: boolean;
    factoring?: boolean;
    invoicingAddressCommonDataId: string;
    invoiceChannel: UniRefund_ContractService_Enums_InvoiceChannel;
    eTaxFree?: boolean;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
    crossTaxFreeForm?: boolean;
    facturaNumberIsUnique?: boolean;
    goodsHaveSerialNumbers?: boolean;
    excludeFromCashLimit?: boolean;
    deskoScanner?: boolean;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isDefault?: boolean;
    referenceNumber: number;
    invoicingFrequency: UniRefund_ContractService_Enums_InvoicingFrequency;
    termOfPayment: number;
    deliveryFee?: boolean;
    factoring?: boolean;
    invoicingAddressCommonData: UniRefund_CRMService_Addresses_AddressDto;
    invoiceChannel: UniRefund_ContractService_Enums_InvoiceChannel;
    eTaxFree?: boolean;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
    crossTaxFreeForm?: boolean;
    facturaNumberIsUnique?: boolean;
    goodsHaveSerialNumbers?: boolean;
    excludeFromCashLimit?: boolean;
    deskoScanner?: boolean;
    contractHeaderId?: string;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingMakeDefaultDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    contractSettingId?: string;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    referenceNumber: number;
    invoicingFrequency: UniRefund_ContractService_Enums_InvoicingFrequency;
    termOfPayment: number;
    deliveryFee?: boolean;
    factoring?: boolean;
    invoicingAddressCommonDataId: string;
    invoiceChannel: UniRefund_ContractService_Enums_InvoiceChannel;
    eTaxFree?: boolean;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
    crossTaxFreeForm?: boolean;
    facturaNumberIsUnique?: boolean;
    goodsHaveSerialNumbers?: boolean;
    excludeFromCashLimit?: boolean;
    deskoScanner?: boolean;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreCreateAndUpdateByListDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    contractStores?: Array<UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreCreateAndUpdateDto> | null;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreCreateAndUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    contractTypeIdentifiersSubId: string;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
    contractSettingId: string;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreDetailedDto = {
    contractTypeIdentifiersSubId: string;
    name?: (string) | null;
    contractSettingId?: string;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
};

export type UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    contractTypeIdentifiersSubId: string;
    contractSettingId: string;
    receiptType: UniRefund_ContractService_Enums_ReceiptType;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaderRefundFeeHeaders_ContractHeaderRefundFeeHeaderCreateAndUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    refundFeeHeaderId: string;
    validFrom: string;
    validTo?: (string) | null;
    isDefault?: boolean;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaderRefundFeeHeaders_ContractHeaderRefundFeeHeaderInformationDto = {
    name: string;
    id: string;
    validFrom: string;
    validTo?: (string) | null;
    isDefault: boolean;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRebateRequestDto = {
    refundMethod?: UniRefund_ContractService_Enums_RefundMethod;
    tagAmounts?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRebateTagAmountDto> | null;
    rebateDate?: string;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRebateResponseDto = {
    tagRebateAmounts?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesTagRebateItem> | null;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRebateTagAmountDto = {
    tagId?: string;
    merchantId?: string;
    sisAmount?: number;
    grossCommission?: number;
    vatRate?: number;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRefundRequestDto = {
    refundMethod?: UniRefund_ContractService_Enums_RefundMethod;
    tagAmounts?: {
        [key: string]: (number);
    } | null;
    refundDate?: string;
    earlyRefund?: boolean;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesForRefundResponseDto = {
    tagRefundAmounts?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesTagRefundItem> | null;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesTagRebateItem = {
    tagId?: string;
    rebateAmount?: number;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_CalculateFeesTagRefundItem = {
    tagId?: string;
    refundAmount?: number;
    touristFee?: number;
    touristBonusFee?: (number) | null;
    agentFee?: number;
    airportFee?: (number) | null;
    earlyRefundFee?: (number) | null;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderDetailForRefundPointDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    contractTypeIdentifier: string;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    refundPointBasicInformationDto?: UniRefund_CRMService_RefundPoints_RefundPointBasicInformationDto;
    isDraft: boolean;
    isEnabled: boolean;
    isActive: boolean;
    validFrom: string;
    validTo?: (string) | null;
    earlyRefund?: boolean;
    contractType: UniRefund_ContractService_Enums_ContractType;
    addressCommonDataId: string;
    refundFeeHeaders: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaderRefundFeeHeaders_ContractHeaderRefundFeeHeaderInformationDto>;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    validFrom: string;
    validTo?: (string) | null;
    addressCommonDataId: string;
    refundFeeHeaders: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaderRefundFeeHeaders_ContractHeaderRefundFeeHeaderCreateAndUpdateDto>;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    contractTypeIdentifier: string;
    isDraft: boolean;
    isEnabled: boolean;
    isActive: boolean;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    contractType: UniRefund_ContractService_Enums_ContractType;
    validFrom: string;
    validTo?: (string) | null;
    earlyRefund?: boolean;
    addressCommonDataId: string;
};

export type UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    webSite?: (string) | null;
    merchantClassification: UniRefund_ContractService_Enums_MerchantClassification;
    status: UniRefund_ContractService_Enums_ContractHeaderStatus;
    validFrom: string;
    validTo?: (string) | null;
    earlyRefund?: boolean;
    addressCommonDataId: string;
    refundFeeHeaders?: Array<UniRefund_ContractService_ContractsForRefundPoint_ContractHeaderRefundFeeHeaders_ContractHeaderRefundFeeHeaderCreateAndUpdateDto> | null;
};

export type UniRefund_ContractService_Enums_ContractHeaderStatus = 'None' | 'Registered' | 'DeRegistrationRequestedByUniRefund' | 'DeRegistrationDataRequestedByAuthorities' | 'SuspendedInternallyAfterDeRegistrationDecline' | 'DeRegisteredAtAuthorities' | 'SuspendedInternallyOnly' | 'SuspensionRequestedByUniRefund' | 'SuspensionRequestedByAuthorities' | 'UnSuspensionRequestedByUniRefund' | 'UnSuspensionRequestedByAuthorities' | 'SuspendedAtAuthorities' | 'UnSuspensionForFurtherDeRegistrationInvitedByAuthorities' | 'UnSuspensionForFurtherDeRegistrationRequestedByUniRefund' | 'Terminated';

export type UniRefund_ContractService_Enums_ContractType = 'Merchant' | 'RefundPoint';

export type UniRefund_ContractService_Enums_FeeType = 'TouristFee' | 'TouristBonusFee' | 'AgentFee' | 'AirportFee' | 'EarlyRefundFee';

export type UniRefund_ContractService_Enums_InvoiceChannel = 'ElectronicInvoice' | 'Email' | 'PaperInvoice';

export type UniRefund_ContractService_Enums_InvoicingFrequency = 'OneTimePerMonth' | 'TwoTimesPerMonth';

export type UniRefund_ContractService_Enums_MerchantClassification = 'Excellent' | 'Good' | 'Satisfactory' | 'Low';

export type UniRefund_ContractService_Enums_RebateStatementPeriod = 'None' | 'Monthly' | 'Quarterly' | 'BiAnnually' | 'Annually';

export type UniRefund_ContractService_Enums_ReceiptType = 'None' | 'NoBarcodeNumber' | 'NoBarcodeText' | 'Barcode' | 'QRCodeIntegration' | 'UniRefundVoucherIntegration';

export type UniRefund_ContractService_Enums_RefundMethod = 'Cash' | 'CreditCard' | 'BankTransfer' | 'Wallet' | 'CashViaPartner';

export type UniRefund_ContractService_Enums_VariableFee = 'PercentOfGC' | 'PercentOfGcWithoutVAT' | 'PercentOfVAT' | 'PercentOfSIS';

export type UniRefund_ContractService_Rebates_MinimumNetCommissions_MinimumNetCommissionDto = {
    id: string;
    amount: number;
    validFrom: string;
    validTo?: (string) | null;
    appliedOrganizationId?: (string) | null;
};

export type UniRefund_ContractService_Rebates_MinimumNetCommissions_MinimumNetCommissionUpSertDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    amount: number;
    validFrom: string;
    validTo?: (string) | null;
    appliedOrganizationId?: (string) | null;
};

export type UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    amount: number;
};

export type UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    amount: number;
    rebateTableHeaderId: string;
};

export type UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailUpdateWithRandomIdDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    amount: number;
};

export type UniRefund_ContractService_Rebates_RebateSettingRebateTableHeaders_RebateSettingRebateTableHeaderInformationDto = {
    name: string;
    id: string;
    validFrom: string;
    validTo?: (string) | null;
};

export type UniRefund_ContractService_Rebates_RebateSettings_RebateSettingDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    referenceNumber?: (string) | null;
    isTrustedMerchant?: boolean;
    rebateStatementPeriod: UniRefund_ContractService_Enums_RebateStatementPeriod;
    affiliationIdForContact: string;
    contractHeaderId: string;
    rebateTableHeaders?: Array<UniRefund_ContractService_Rebates_RebateSettingRebateTableHeaders_RebateSettingRebateTableHeaderInformationDto> | null;
    minimumNetCommissions?: Array<UniRefund_ContractService_Rebates_MinimumNetCommissions_MinimumNetCommissionDto> | null;
};

export type UniRefund_ContractService_Rebates_RebateSettings_RebateSettingUpSertDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    referenceNumber?: (string) | null;
    isTrustedMerchant?: (boolean) | null;
    rebateStatementPeriod: UniRefund_ContractService_Enums_RebateStatementPeriod;
    affiliationIdForContact: string;
    rebateTableHeaders?: Array<UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeadersToRebateSettingUpSertDto> | null;
    minimumNetCommissions?: Array<UniRefund_ContractService_Rebates_MinimumNetCommissions_MinimumNetCommissionUpSertDto> | null;
};

export type UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    fixedFeeValue: number;
    percentFeeValue: number;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
    variableFee: UniRefund_ContractService_Enums_VariableFee;
};

export type UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    fixedFeeValue: number;
    percentFeeValue: number;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
    variableFee: UniRefund_ContractService_Enums_VariableFee;
    rebateTableHeaderId: string;
};

export type UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailUpdateWithRandomIdDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    fixedFeeValue: number;
    percentFeeValue: number;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
    variableFee: UniRefund_ContractService_Enums_VariableFee;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderCreateDto = {
    name: string;
    calculateNetCommissionInsteadOfRefund: boolean;
    isTemplate: boolean;
    merchantId?: (string) | null;
    rebateTableDetails?: Array<UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailCreateDto> | null;
    processingFeeDetails?: Array<UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailCreateDto> | null;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    calculateNetCommissionInsteadOfRefund: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    merchantId?: (string) | null;
    merchantName?: (string) | null;
    sourceTemplateId?: (string) | null;
    rebateTableDetails?: Array<UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailDto> | null;
    processingFeeDetails?: Array<UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailDto> | null;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderInformationDto = {
    id: string;
    name: string;
    isTemplate: boolean;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderListDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    calculateNetCommissionInsteadOfRefund: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    merchantId?: (string) | null;
    merchantName?: (string) | null;
    sourceTemplateId?: (string) | null;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeadersToRebateSettingUpSertDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    rebateTableHeaderId: string;
    validFrom: string;
    validTo?: (string) | null;
};

export type UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderUpdateDto = {
    name: string;
    calculateNetCommissionInsteadOfRefund?: boolean;
    rebateTableDetails?: Array<UniRefund_ContractService_Rebates_RebateTableDetails_RebateTableDetailUpdateWithRandomIdDto> | null;
    processingFeeDetails?: Array<UniRefund_ContractService_Rebates_ProcessingFeeDetails_ProcessingFeeDetailUpdateWithRandomIdDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    amountFrom: number;
    amountTo: number;
    fixedFeeValue: number;
    percentFeeValue: number;
    minFee: number;
    maxFee: number;
    feeType: UniRefund_ContractService_Enums_FeeType;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
};

export type UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    amountFrom: number;
    amountTo: number;
    fixedFeeValue: number;
    percentFeeValue: number;
    minFee: number;
    maxFee: number;
    feeType: UniRefund_ContractService_Enums_FeeType;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
};

export type UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailUpdateWithRandomIdDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    amountFrom: number;
    amountTo: number;
    fixedFeeValue: number;
    percentFeeValue: number;
    minFee: number;
    maxFee: number;
    feeType: UniRefund_ContractService_Enums_FeeType;
    refundMethod: UniRefund_ContractService_Enums_RefundMethod;
};

export type UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isActive: boolean;
    isTemplate: boolean;
    refundPointId?: (string) | null;
    refundFeeDetails?: Array<UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailCreateDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isActive: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    refundPointId?: (string) | null;
    refundPointName?: (string) | null;
    sourceTemplateId?: (string) | null;
    refundFeeDetails?: Array<UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderInformationDto = {
    id: string;
    name: string;
    isTemplate: boolean;
};

export type UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderListDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isActive: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    refundPointId?: (string) | null;
    refundPointName?: (string) | null;
    sourceTemplateId?: (string) | null;
};

export type UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isActive: boolean;
    refundFeeDetails?: Array<UniRefund_ContractService_Refunds_RefundFeeDetails_RefundFeeDetailUpdateWithRandomIdDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    vatRate: number;
    minValue: number;
    maxValue: number;
    refundAmount: number;
    refundPercent: number;
    isLoyalty: boolean;
};

export type UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    vatRate: number;
    minValue: number;
    maxValue: number;
    refundAmount: number;
    refundPercent: number;
    isLoyalty: boolean;
};

export type UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailUpdateWithRandomIdDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    vatRate: number;
    minValue: number;
    maxValue: number;
    refundAmount: number;
    refundPercent: number;
    isLoyalty: boolean;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault: boolean;
    isBundling: boolean;
    isTemplate: boolean;
    merchantId?: (string) | null;
    refundTableDetails?: Array<UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailCreateDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isDefault: boolean;
    isBundling: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    merchantId?: (string) | null;
    merchantName?: (string) | null;
    sourceTemplateId?: (string) | null;
    refundTableDetails?: Array<UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailDto> | null;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderForTagDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isDefault: boolean;
    isBundling: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    merchantId?: (string) | null;
    merchantName?: (string) | null;
    sourceTemplateId?: (string) | null;
    refundTableDetails?: Array<UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailDto> | null;
    contractHeaderId?: string;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderInformationDto = {
    id: string;
    name: string;
    isTemplate: boolean;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderListDto = {
    id: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name: string;
    isDefault: boolean;
    isBundling: boolean;
    isTemplate: boolean;
    isAssigned: boolean;
    isEditable: boolean;
    isCustomizedOverTemplate?: (boolean) | null;
    merchantId?: (string) | null;
    merchantName?: (string) | null;
    sourceTemplateId?: (string) | null;
};

export type UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault: boolean;
    isBundling: boolean;
    refundTableDetails?: Array<UniRefund_ContractService_Refunds_RefundTableDetails_RefundTableDetailUpdateWithRandomIdDto> | null;
};

export type UniRefund_CRMService_Addresses_AddressDto = {
    id?: string;
    partyType: UniRefund_Shared_Contracts_Enums_PartyType;
    partyId: string;
    countryId: string;
    adminAreaLevel1Id: string;
    adminAreaLevel2Id: string;
    neighborhoodId: string;
    addressLine: string;
    postalCode?: (string) | null;
    type: UniRefund_CRMService_Addresses_AddressType;
    placeId?: (string) | null;
    latitude?: (number) | null;
    longitude?: (number) | null;
    isPrimary: boolean;
};

export type UniRefund_CRMService_Addresses_AddressType = 'UNKNOWN' | 'HOME' | 'WORK';

export type UniRefund_CRMService_Individuals_IndividualIdNameDto = {
    id?: string;
    name: string;
};

export type UniRefund_CRMService_Merchants_MerchantBasicInformationDto = {
    id?: string;
    name: string;
    taxOffice: UniRefund_CRMService_TaxOffices_TaxOfficeNameDto;
    numberOfStores: number;
    accountManagers: Array<UniRefund_CRMService_Individuals_IndividualIdNameDto>;
};

export type UniRefund_CRMService_RefundPoints_RefundPointBasicInformationDto = {
    id?: string;
    name?: (string) | null;
    taxOffice?: UniRefund_CRMService_TaxOffices_TaxOfficeNameDto;
    numberOfStores?: number;
    accountManagers?: Array<UniRefund_CRMService_Individuals_IndividualIdNameDto> | null;
};

export type UniRefund_CRMService_TaxOffices_TaxOfficeNameDto = {
    id: string;
    name: string;
};

export type UniRefund_Shared_Contracts_Enums_PartyType = 'INDIVIDUAL' | 'MERCHANT' | 'REFUNDPOINT' | 'CUSTOM' | 'TAXFREE' | 'TAXOFFICE' | 'TOURGUIDE' | 'TRAVELLER';

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type GetApiContractServiceMerchantsContractsContractHeadersByIdData = {
    id: string;
};

export type GetApiContractServiceMerchantsContractsContractHeadersByIdResponse = (UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderDetailForMerchantDto);

export type PutApiContractServiceMerchantsContractsContractHeadersByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantUpdateDto;
};

export type PutApiContractServiceMerchantsContractsContractHeadersByIdResponse = (UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderDetailForMerchantDto);

export type DeleteApiContractServiceMerchantsContractsContractHeadersByIdData = {
    id: string;
};

export type DeleteApiContractServiceMerchantsContractsContractHeadersByIdResponse = (unknown);

export type GetApiContractServiceMerchantsContractsContractHeadersData = {
    isDraft?: boolean;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceMerchantsContractsContractHeadersResponse = (PagedResultDto_ContractHeaderForMerchantDto);

export type GetApiContractServiceMerchantsByIdContractsContractHeadersData = {
    id: string;
    isDraft?: boolean;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceMerchantsByIdContractsContractHeadersResponse = (PagedResultDto_ContractHeaderDetailForMerchantDto);

export type PostApiContractServiceMerchantsByIdContractsContractHeadersData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderForMerchantCreateDto;
};

export type PostApiContractServiceMerchantsByIdContractsContractHeadersResponse = (UniRefund_ContractService_ContractsForMerchant_ContractHeaders_ContractHeaderDetailForMerchantDto);

export type PostApiContractServiceMerchantsContractsContractHeadersByIdValidateData = {
    id: string;
};

export type PostApiContractServiceMerchantsContractsContractHeadersByIdValidateResponse = (boolean);

export type PutApiContractServiceMerchantsContractsContractHeadersByIdMakePassiveData = {
    id: string;
};

export type PutApiContractServiceMerchantsContractsContractHeadersByIdMakePassiveResponse = (unknown);

export type GetApiContractServiceMerchantsContractsContractHeadersByIdRebateSettingsData = {
    id: string;
};

export type GetApiContractServiceMerchantsContractsContractHeadersByIdRebateSettingsResponse = (UniRefund_ContractService_Rebates_RebateSettings_RebateSettingDto);

export type PostApiContractServiceMerchantsContractsContractHeadersByIdRebateSettingsData = {
    id: string;
    requestBody?: UniRefund_ContractService_Rebates_RebateSettings_RebateSettingUpSertDto;
};

export type PostApiContractServiceMerchantsContractsContractHeadersByIdRebateSettingsResponse = (UniRefund_ContractService_Rebates_RebateSettings_RebateSettingDto);

export type GetApiContractServiceMerchantsContractsContractSettingsByIdData = {
    id: string;
};

export type GetApiContractServiceMerchantsContractsContractSettingsByIdResponse = (UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto);

export type PutApiContractServiceMerchantsContractsContractSettingsByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingUpdateDto;
};

export type PutApiContractServiceMerchantsContractsContractSettingsByIdResponse = (UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto);

export type DeleteApiContractServiceMerchantsContractsContractSettingsByIdData = {
    id: string;
};

export type DeleteApiContractServiceMerchantsContractsContractSettingsByIdResponse = (unknown);

export type GetApiContractServiceMerchantsContractsContractHeadersByIdContractSettingsData = {
    id: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceMerchantsContractsContractHeadersByIdContractSettingsResponse = (PagedResultDto_ContractSettingDto);

export type PostApiContractServiceMerchantsContractsContractHeadersByIdContractSettingsData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingCreateDto;
};

export type PostApiContractServiceMerchantsContractsContractHeadersByIdContractSettingsResponse = (UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto);

export type PutApiContractServiceMerchantsContractsContractHeadersByIdSetDefaultSettingData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingMakeDefaultDto;
};

export type PutApiContractServiceMerchantsContractsContractHeadersByIdSetDefaultSettingResponse = (UniRefund_ContractService_ContractsForMerchant_ContractSettings_ContractSettingDto);

export type GetApiContractServiceMerchantsContractsContractHeadersByIdContractStoresData = {
    id: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceMerchantsContractsContractHeadersByIdContractStoresResponse = (PagedResultDto_ContractStoreDetailedDto);

export type PostApiContractServiceMerchantsContractsContractHeadersByIdContractStoresData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreCreateAndUpdateByListDto;
};

export type PostApiContractServiceMerchantsContractsContractHeadersByIdContractStoresResponse = (Array<UniRefund_ContractService_ContractsForMerchant_ContractStores_ContractStoreDto>);

export type GetApiContractServiceRefundPointsContractsContractHeadersByIdData = {
    id: string;
};

export type GetApiContractServiceRefundPointsContractsContractHeadersByIdResponse = (UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderDetailForRefundPointDto);

export type PutApiContractServiceRefundPointsContractsContractHeadersByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointUpdateDto;
};

export type PutApiContractServiceRefundPointsContractsContractHeadersByIdResponse = (UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderDetailForRefundPointDto);

export type DeleteApiContractServiceRefundPointsContractsContractHeadersByIdData = {
    id: string;
};

export type DeleteApiContractServiceRefundPointsContractsContractHeadersByIdResponse = (unknown);

export type GetApiContractServiceRefundPointsContractsContractHeadersData = {
    isDraft?: boolean;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceRefundPointsContractsContractHeadersResponse = (PagedResultDto_ContractHeaderForRefundPointDto);

export type GetApiContractServiceRefundPointsByIdContractsContractHeadersData = {
    id: string;
    isDraft?: boolean;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceRefundPointsByIdContractsContractHeadersResponse = (PagedResultDto_ContractHeaderDetailForRefundPointDto);

export type PostApiContractServiceRefundPointsByIdContractsContractHeadersData = {
    id: string;
    requestBody?: UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderForRefundPointCreateDto;
};

export type PostApiContractServiceRefundPointsByIdContractsContractHeadersResponse = (UniRefund_ContractService_ContractsForRefundPoint_ContractHeaders_ContractHeaderDetailForRefundPointDto);

export type PostApiContractServiceRefundPointsContractsContractHeadersByIdValidateData = {
    id: string;
};

export type PostApiContractServiceRefundPointsContractsContractHeadersByIdValidateResponse = (boolean);

export type PutApiContractServiceRefundPointsContractsContractHeadersByIdMakePassiveData = {
    id: string;
};

export type PutApiContractServiceRefundPointsContractsContractHeadersByIdMakePassiveResponse = (unknown);

export type GetApiContractServiceRebateTableHeadersAssignablesByMerchantData = {
    merchantId: string;
    sorting?: string;
};

export type GetApiContractServiceRebateTableHeadersAssignablesByMerchantResponse = (Array<UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderInformationDto>);

export type GetApiContractServiceRebateTableHeadersByIdData = {
    id: string;
};

export type GetApiContractServiceRebateTableHeadersByIdResponse = (UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderDto);

export type PutApiContractServiceRebateTableHeadersByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderUpdateDto;
};

export type PutApiContractServiceRebateTableHeadersByIdResponse = (UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderDto);

export type GetApiContractServiceRebateTableHeadersData = {
    isTemplate?: boolean;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiContractServiceRebateTableHeadersResponse = (PagedResultDto_RebateTableHeaderListDto);

export type PostApiContractServiceRebateTableHeadersData = {
    requestBody?: UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderCreateDto;
};

export type PostApiContractServiceRebateTableHeadersResponse = (UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderDto);

export type PostApiContractServiceRebateTableHeadersCloneByIdData = {
    id: string;
    isTemplate: boolean;
    merchantId?: string;
};

export type PostApiContractServiceRebateTableHeadersCloneByIdResponse = (UniRefund_ContractService_Rebates_RebateTableHeaders_RebateTableHeaderDto);

export type GetApiContractServiceRefundFeeHeadersAssignablesByRefundPointData = {
    refundPointId: string;
    sorting?: string;
};

export type GetApiContractServiceRefundFeeHeadersAssignablesByRefundPointResponse = (Array<UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderInformationDto>);

export type GetApiContractServiceRefundFeeHeadersByIdData = {
    id: string;
};

export type GetApiContractServiceRefundFeeHeadersByIdResponse = (UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderDto);

export type PutApiContractServiceRefundFeeHeadersByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderUpdateDto;
};

export type PutApiContractServiceRefundFeeHeadersByIdResponse = (UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderDto);

export type GetApiContractServiceRefundFeeHeadersData = {
    isTemplate?: boolean;
    maxResultCount?: number;
    skipCount?: number;
};

export type GetApiContractServiceRefundFeeHeadersResponse = (PagedResultDto_RefundFeeHeaderListDto);

export type PostApiContractServiceRefundFeeHeadersData = {
    requestBody?: UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderCreateDto;
};

export type PostApiContractServiceRefundFeeHeadersResponse = (UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderDto);

export type PostApiContractServiceRefundFeeHeadersCloneByIdData = {
    id: string;
    isTemplate: boolean;
    refundPointId?: string;
};

export type PostApiContractServiceRefundFeeHeadersCloneByIdResponse = (UniRefund_ContractService_Refunds_RefundFeeHeaders_RefundFeeHeaderDto);

export type GetApiContractServiceRefundFeeHeadersPaymentTypesByRefundPointByRefundPointIdData = {
    refundPointId: string;
};

export type GetApiContractServiceRefundFeeHeadersPaymentTypesByRefundPointByRefundPointIdResponse = (Array<UniRefund_ContractService_Enums_RefundMethod>);

export type GetApiContractServiceRefundTableHeadersAssignablesByMerchantData = {
    merchantId: string;
    sorting?: string;
};

export type GetApiContractServiceRefundTableHeadersAssignablesByMerchantResponse = (Array<UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderInformationDto>);

export type GetApiContractServiceRefundTableHeadersByIdData = {
    id: string;
};

export type GetApiContractServiceRefundTableHeadersByIdResponse = (UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderDto);

export type PutApiContractServiceRefundTableHeadersByIdData = {
    id: string;
    requestBody?: UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderUpdateDto;
};

export type PutApiContractServiceRefundTableHeadersByIdResponse = (UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderDto);

export type GetApiContractServiceRefundTableHeadersData = {
    isTemplate?: boolean;
    maxResultCount?: number;
    skipCount?: number;
};

export type GetApiContractServiceRefundTableHeadersResponse = (PagedResultDto_RefundTableHeaderListDto);

export type PostApiContractServiceRefundTableHeadersData = {
    requestBody?: UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderCreateDto;
};

export type PostApiContractServiceRefundTableHeadersResponse = (UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderDto);

export type PostApiContractServiceRefundTableHeadersCloneByIdData = {
    id: string;
    isTemplate: boolean;
    merchantId?: string;
};

export type PostApiContractServiceRefundTableHeadersCloneByIdResponse = (UniRefund_ContractService_Refunds_RefundTableHeaders_RefundTableHeaderDto);